export const HAZARD_LIST_REQUEST = 'HAZARD_LIST_REQUEST'
export const HAZARD_LIST_SUCCESS = 'HAZARD_LIST_SUCCESS'
export const HAZARD_LIST_FAIL = 'HAZARD_LIST_FAIL'

export const HAZARD_LIST_FOR_USER_REQUEST = 'HAZARD_LIST_FOR_USER_REQUEST'
export const HAZARD_LIST_FOR_USER_SUCCESS = 'HAZARD_LIST_FOR_USER_SUCCESS'
export const HAZARD_LIST_FOR_USER_FAIL = 'HAZARD_LIST_FOR_USER_FAIL'

export const HAZARD_DETAILS_REQUEST = 'HAZARD_DETAILS_REQUEST'
export const HAZARD_DETAILS_SUCCESS = 'HAZARD_DETAILS_SUCCESS'
export const HAZARD_DETAILS_FAIL = 'HAZARD_DETAILS_FAIL'

export const HAZARD_DELETE_REQUEST = 'HAZARD_DELETE_REQUEST'
export const HAZARD_DELETE_SUCCESS = 'HAZARD_DELETE_SUCCESS'
export const HAZARD_DELETE_FAIL = 'HAZARD_DELETE_FAIL'

export const HAZARD_CREATE_REQUEST = 'HAZARD_CREATE_REQUEST'
export const HAZARD_CREATE_SUCCESS = 'HAZARD_CREATE_SUCCESS'
export const HAZARD_CREATE_FAIL = 'HAZARD_CREATE_FAIL'
export const HAZARD_CREATE_RESET = 'HAZARD_CREATE_RESET'

export const HAZARD_UPDATE_REQUEST = 'HAZARD_UPDATE_REQUEST'
export const HAZARD_UPDATE_SUCCESS = 'HAZARD_UPDATE_SUCCESS'
export const HAZARD_UPDATE_FAIL = 'HAZARD_UPDATE_FAIL'
export const HAZARD_UPDATE_RESET = 'HAZARD_UPDATE_RESET'

export const HAZARD_CREATE_REVIEW_REQUEST = 'HAZARD_CREATE_REVIEW_REQUEST'
export const HAZARD_CREATE_REVIEW_SUCCESS = 'HAZARD_CREATE_REVIEW_SUCCESS'
export const HAZARD_CREATE_REVIEW_FAIL = 'HAZARD_CREATE_REVIEW_FAIL'
export const HAZARD_CREATE_REVIEW_RESET = 'HAZARD_CREATE_REVIEW_RESET'

export const HAZARD_TOP_REQUEST = 'HAZARD_TOP_REQUEST'
export const HAZARD_TOP_SUCCESS = 'HAZARD_TOP_SUCCESS'
export const HAZARD_TOP_FAIL = 'HAZARD_TOP_FAIL'